#!/bin/sh

export FINAL_OBJ=$PWD/obj/
export PLATFORM_EXE=sim
export PLATFORM_OS=linux


if [ "$1" = "" ]; then
	echo "Building TM Virtual Lib"
	export CODE_DIR=$PWD
	make -C .
else
	echo "Cleaning SIM Lib"
	export CODE_DIR=$PWD
	make $1 -C .
fi
if [ $? = 0 ]; then
	echo "Sucessfully Done"
else
	echo "Build Failure"
fi
