#Base Makefile
obj-$(CONFIG_OPENSWITCH_TCP_IP) += arp/
obj-$(CONFIG_OPENSWITCH_TCP_IP) += tcp/
obj-$(CONFIG_OPENSWITCH_TCP_IP) += udp/
obj-$(CONFIG_OPENSWITCH_TCP_IP) += dhcp/
obj-$(CONFIG_OPENSWITCH_TCP_IP) += ipv4/
obj-$(CONFIG_OPENSWITCH_TCP_IP) += dns/
obj-$(CONFIG_OPENSWITCH_TCP_IP) += sockets/

obj-y += bridge/
obj-y += init/
obj-y += cli/
obj-y += platform/
obj-y += lib/

obj-$(CONFIG_TELNET) += telnetd/
obj-$(CONFIG_ZEBRA_RTM) += rtm/
obj-$(CONFIG_TRACE_ROUTE) += traceroute/
obj-$(CONFIG_DHCP_SERVER) += dhcpserver/
